// packages/vue/src/OvO.vue
<template>
  <div></div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import OvO from "@ovojs/ovo";
import "@ovojs/ovo/dist/style.css";
import { OvOProps } from "./types";

export default defineComponent({
  // What the fuck is this boilerplatable shit?
  props: ['server', 'placeholder', 'emoji', 'timeout'],
  name: "OvO",
  mounted() {
    new OvO({
      target: this.$el,
      props: this.$props as OvOProps
    })
  }
})
</script>

// packages/react/src/ovo.tsx
import React, { useEffect, useRef } from "react";
import O from "@ovojs/ovo";
import { OvOProps } from "./types";
import "@ovojs/ovo/dist/style.css";

export default function OvO(props: OvOProps): JSX.Element {

  const ref = useRef<HTMLDivElement>(null);

  useEffect(function () {
    if (!ref.current) return;

    const o = new O({
      target: ref.current,
      props
    })

    return function () {
      o.$destroy();
    }
  }, []);

  return <div ref={ref}></div>
}
